[package]
name = "The Guar Whisperer"
description = "Allows your to tame and breed guars, and keep them as companions."
homepage = "https://www.nexusmods.com/morrowind/mods/48247"
repository = "https://github.com/jhaakma/theGuarWhisperer"
authors = [ "Merlord",]
version = "1.4.0"

[dependencies]
assets = [ "TheGuarWhisperer.esp", "Icons/mer_tgw", "Meshes/mer_tgw", "MWSE/mods/mer/theGuarWhisperer",]

[dependencies.mwse]
buildnumber = 3423

[dependencies.mge-xe]
version = ">=0.15.0"

[tools.mwse]
lua-mod = "mer.theGuarWhisperer"

[dependencies.mods."The Crafting Framework"]
mwse-module = "CraftingFramework"
version = "^1.18.0"
url = "https://www.nexusmods.com/morrowind/mods/51009?tab=files"
